services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
    command:
      - "--label-enable"
      - "--interval"
      - "60"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json

  reverse-proxy:
    image: traefik:v3.1
    restart: always
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.sentinelresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.sentinelresolver.acme.email=res@hubku.com"
      - "--certificatesresolvers.sentinelresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  pgbackweb:
    image: eduardolat/pgbackweb:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgbackweb.rule=Host(`cron.hubku.com`)"
      - "traefik.http.routers.pgbackweb.entrypoints=websecure"
      - "traefik.http.routers.pgbackweb.tls.certresolver=sentinelresolver"
    volumes:
      - ./backups:/backups 
    environment:
      PBW_ENCRYPTION_KEY: "PfZ7ervYM4D9ER8btT5usCUqKphVkmzNSXjawFAWgyB2JLHx"
      PBW_POSTGRES_CONN_STRING: "postgres://postgres:h8fzpak29JBQ63wrXjyxEZuAPqvKmGbWsSLHMRD5tg47NnFY@sentinel-pgbw:5432/pgbw?sslmode=disable"
      TZ: "Asia/Jakarta"
    depends_on:
      sentinel-pgbw:
        condition: service_healthy

  sentinel:
    image: ghcr.io/hubkudev/sentinel:prod
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentinel.rule=Host(`sentinel.hubku.com`)"
      - "traefik.http.routers.sentinel.entrypoints=websecure"
      - "traefik.http.services.sentinel.loadbalancer.server.port=8080"
      - "traefik.http.routers.sentinel.tls.certresolver=sentinelresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PORT=8080
      - POSTGRES_HOST=sentinel-pg
      - POSTGRES_PASSWORD=Jjmkzy27evZQPnStgbLRaTwWpH9xcXVB
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sentinel-alpha
      - POSTGRES_PORT=5432
      - REDIS_HOST=sentinel-redis
      - REDIS_PORT=6379
      - G_CLIENT=407555103150-n89fabccd4m6d0lr9jqom33uo0iefn5v.apps.googleusercontent.com
      - G_SECRET=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
      - G_REDIRECT=https://sentinel.hubku.com/auth/google/callback
      - COOKIE_SALT=kX7jxLAtynRdMVmpJHgUq94swa3urbGS
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      sentinel-pg:
        condition: service_healthy
      sentinel-redis:
        condition: service_healthy

  sentinel-pg:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: sentinel-alpha
      POSTGRES_PASSWORD: Jjmkzy27evZQPnStgbLRaTwWpH9xcXVB
    volumes:
      - sentinel-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-pgbw:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: pgbw
      POSTGRES_PASSWORD: h8fzpak29JBQ63wrXjyxEZuAPqvKmGbWsSLHMRD5tg47NnFY
    volumes:
      - sentinel-pgbw:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sentinel-redis:
    image: redis:7.4.1
    restart: always
    environment:
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sentinel-data:
  sentinel-pgbw:
  letsencrypt:
